language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "12"
  - "10"
  - "8"

install:
  - npm install

script:
  - npm test
  - npm run linter
  - npm run build

cache:
  directories:
    - "node_modules"
