export const DATE_FORMAT = 'YYYY-MM-DD HH:mm';
export const S3_ACCESS_KEY_ENV = 'SIEGEBOT_LFG_S3_ACCESS';
export const S3_SECRET_ENV = 'SIEGEBOT_LFG_S3_SECRET';
export const S3_REGION_ENV = 'SIEGEBOT_LFG_S3_REGION';
export const S3_BUCKET_ENV = 'SIEGEBOT_LFG_S3_BUCKET';